# Natural Language Processing - Lyric Analysis and Visualization

### Cleaning and Preparing Data

In [38]:
import numpy as np 
import pandas as pd 
import re
import os

Setting the path to the album and tabular data folders and creating a list of album paths and song paths

In [39]:
path_to_album = './data/Albums/'
album_list = [os.path.join(path_to_album, album) for album in os.listdir(path_to_album)]
album_list

['./data/Albums/evermore_theforeveristhesweetestconchapter',
 './data/Albums/AllTooWell_10MinuteVersion__TheShortFilm__EP',
 './data/Albums/MessageInABottle_FatMaxGRemix__TaylorsVersion_',
 './data/Albums/Fearless_TaylorsVersion_',
 './data/Albums/Red_TaylorsVersion__CouldYouBeTheOneChapter',
 './data/Albums/TheMoreRed_TaylorsVersion_Chapter',
 './data/Albums/Carolina_FromTheMotionPictureWhereTheCrawdadsSing_',
 './data/Albums/LavenderHaze_Remixes_',
 './data/Albums/Red_TaylorsVersion__SheWroteASongAboutMeChapter',
 './data/Albums/Lover',
 './data/Albums/theladieslunchingchapter',
 './data/Albums/.DS_Store',
 './data/Albums/Midnights_TargetExclusive_',
 './data/Albums/Fearless_TaylorsVersion__TheHalfwayOuttheDoorChapter',
 './data/Albums/1989',
 './data/Albums/Red_TaylorsVersion__TheSlowMotionChapter',
 './data/Albums/Fearless_TaylorsVersion__TheIRememberWhatYouSaidLastNightChapter',
 './data/Albums/TaylorSwift',
 './data/Albums/Evermore',
 './data/Albums/evermore_JapaneseEdition_',
 './data/Albums/Reputation',
 './data/Albums/Midnights',
 './data/Albums/Midnights_TheTillDawnEdition_',
 './data/Albums/evermore_deluxeversion_',
 './data/Albums/Lover_LiveFromParis_HeartShapedVinyl',
 './data/Albums/folklore_thelongpondstudiosessions_RecordStoreDayExclusive_',
 './data/Albums/Red_TaylorsVersion_',
 './data/Albums/Anti_Hero_Remixes_',
 './data/Albums/Midnights_3amEdition_',
 './data/Albums/Red_TaylorsVersion__FromTheVaultChapter',
 './data/Albums/Red',
 './data/Albums/evermore_thedroppedyourhandwhiledancingchapter',
 './data/Albums/Folklore',
 './data/Albums/SpeakNow_WorldTourLive',
 './data/Albums/TheMoreLoverChapter',
 './data/Albums/Fearless_TaylorsVersion__TheFromtheVaultChapter',
 './data/Albums/SpeakNow_TaylorsVersion_',
 './data/Albums/SpeakNow_Deluxe_',
 './data/Albums/evermore_digitallyautographedfanedition_',
 './data/Albums/Midnights_AppleMusicExclusive_',
 './data/Albums/Fearless_PlatinumEdition_',
 './data/Albums/TheMoreFearless_TaylorsVersion_Chapter',
 './data/Albums/SpeakNow',
 './data/Albums/Fearless_TaylorsVersion__TheKissingInTheRainChapter',
 './data/Albums/Midnights_TheLateNightEdition_',
 './data/Albums/thelakes_7_Single_RecordStoreDayExclusive_',
 './data/Albums/Fearless']

The tabular folder has tables for each album and within each album folder we have songs. So, now, we will use the tabular table to map the paths above.

In [40]:
tabular_path = './data/Tabular/'
songs_list = [os.path.join(tabular_path, song) for song in os.listdir(tabular_path)]
songs_list

['./data/Tabular/SpeakNow_WorldTourLive.csv',
 './data/Tabular/Anti_Hero_Remixes_.csv',
 './data/Tabular/Red.csv',
 './data/Tabular/Fearless_PlatinumEdition_.csv',
 './data/Tabular/Fearless_Taylor_sVersion__TheKissingInTheRainChapter.csv',
 './data/Tabular/Red_Taylor_sVersion_.csv',
 './data/Tabular/Carolina_FromTheMotionPicture_WhereTheCrawdadsSing__.csv',
 './data/Tabular/LavenderHaze_Remixes_.csv',
 './data/Tabular/MessageInABottle_FatMaxGRemix__Taylor_sVersion_.csv',
 './data/Tabular/Midnights_AppleMusicExclusive_.csv',
 './data/Tabular/Red_Taylor_sVersion__FromTheVaultChapter.csv',
 './data/Tabular/Midnights_TheTilDawnEdition_.csv',
 './data/Tabular/Red_Taylor_sVersion__SheWroteASongAboutMeChapter.csv',
 './data/Tabular/Reputation.csv',
 './data/Tabular/Midnights_TargetExclusive_.csv',
 './data/Tabular/Fearless_Taylor_sVersion_.csv',
 './data/Tabular/TheMoreRed_Taylor_sVersion_Chapter.csv',
 './data/Tabular/folklore_thelongpondstudiosessions_RecordStoreDayExclusive_.csv',
 './data/Tabular/Red_Taylor_sVersion__CouldYouBeTheOneChapter.csv',
 './data/Tabular/Fearless_Taylor_sVersion__TheFromtheVaultChapter.csv',
 './data/Tabular/evermore_the_foreveristhesweetestcon_chapter.csv',
 './data/Tabular/SpeakNow.csv',
 './data/Tabular/SpeakNow_Taylor_sVersion_.csv',
 './data/Tabular/Midnights_TheTillDawnEdition_.csv',
 './data/Tabular/Fearless_Taylor_sVersion__TheIRememberWhatYouSaidLastNightChapter.csv',
 './data/Tabular/TheMoreFearless_Taylor_sVersion_Chapter.csv',
 './data/Tabular/Evermore.csv',
 './data/Tabular/Midnights_3amEdition_.csv',
 './data/Tabular/Lover_LiveFromParis_HeartShapedVinyl.csv',
 './data/Tabular/evermore_deluxeversion_.csv',
 './data/Tabular/Midnights.csv',
 './data/Tabular/evermore_JapaneseEdition_.csv',
 './data/Tabular/TaylorSwift.csv',
 './data/Tabular/Lover.csv',
 './data/Tabular/TheMoreLoverChapter.csv',
 './data/Tabular/evermore_digitallyautographedfanedition_.csv',
 './data/Tabular/thelakes_7_Single_RecordStoreDayExclusive_.csv',
 './data/Tabular/the_ladieslunching_chapter.csv',
 './data/Tabular/AllTooWell_10MinuteVersion__TheShortFilm__EP.csv',
 './data/Tabular/Midnights_TheLateNightEdition_.csv',
 './data/Tabular/Fearless_Taylor_sVersion__TheHalfwayOuttheDoorChapter.csv',
 './data/Tabular/Folklore.csv',
 './data/Tabular/Red_Taylor_sVersion__TheSlowMotionChapter.csv',
 './data/Tabular/SpeakNow_Deluxe_.csv',
 './data/Tabular/evermore_thedroppedyourhandwhiledancingchapter.csv',
 './data/Tabular/1989.csv']

Loading the album data from the CSV file into a DataFrame and then showing the first few rows of the DataFrame.

In [41]:
album_df = pd.read_csv('./data/Albums.csv', index_col=0)
album_df.head()

        ID                                             Albums
0   758025                       Speak Now (Taylor’s Version)
1  1040217                 Midnights (The Late Night Edition)
2  1040211                   Midnights (The Til Dawn Edition)
3  1027134  folklore: the long pond studio sessions (Recor...
4  1013719            The More Red (Taylor’s Version) Chapter

In [42]:
album_df['Track_path'] = album_df.Albums.apply(lambda x : os.path.join(tabular_path, re.sub('[^a-zA-Z0-9_]','_',''.join(x.split()))+'.csv'))
album_df.head()

,ID,Albums,Track_path
0,758025,Speak Now (Taylor’s Version),./data/Tabular/SpeakNow_Taylor_sVersion_.csv
1,1040217,Midnights (The Late Night Edition),./data/Tabular/Midnights_TheLateNightEdition_.csv
2,1040211,Midnights (The Til Dawn Edition),./data/Tabular/Midnights_TheTilDawnEdition_.csv
3,1027134,folklore: the long pond studio sessions (Recor...,./data/Tabular/folklore_thelongpondstudiosessi...
4,1013719,The More Red (Taylor’s Version) Chapter,./data/Tabular/TheMoreRed_Taylor_sVersion_Chap...

In [43]:
album_df.loc[0,'Track_path']

'./data/Tabular/SpeakNow_Taylor_sVersion_.csv'

Fetching all songs within each album

In [44]:
df = pd.DataFrame()
for ind, album in enumerate(album_df['Track_path']):
    try:
        track_df = pd.read_csv(album)
        track_df['Album_ID'] = album_df.loc[ind]['ID']
        track_df['Album'] = album_df.loc[ind]['Albums']
        track_df['Album_Path'] = os.path.join(path_to_album, re.sub('[^a-zA-Z0-9_]','_',''.join(album_df.loc[ind]['Albums'].split())))
        df = pd.concat([df, track_df])
    except Exception as e:
        print('No songs in album: ',album )
        pass

df

,Unnamed: 0,ID,Tracks,Album_ID,Album,Album_Path
0,0,6688213,Mine (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
1,1,6688225,Sparks Fly (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
2,2,6688226,Back To December (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
3,3,6688227,Speak Now (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
4,4,6688228,Dear John (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
...,...,...,...,...,...,...
18,18,8486447,"Wouldve, Couldve, Shouldve",1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_
19,19,8486436,Dear Reader,1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_
20,20,8461583,Hits Different,1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_
21,21,9157481,Snow On The Beach (feat. More Lana Del Rey),1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_
22,22,9157172,Karma (Remix),1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_

In [45]:
df.reset_index(drop=True, inplace=True)
df.drop('Unnamed: 0', axis=1, inplace=True)

In [46]:
df.loc[30,'Album_Path']

'./data/Albums/Midnights_TheLateNightEdition_'

In [47]:
df.loc[30,'Tracks']

'Bejeweled'

In [48]:
def get_lyrics(x):
    path = (x['Album_Path'] + '/' +re.sub('[^a-zA-Z0-9_]','_',''.join(x['Tracks'].split())) + '.txt').replace('_s', 's').replace('the_ladieslunching_chapter', 'theladieslunchingchapter').replace('Carolina_FromTheMotionPicture_WhereTheCrawdadsSing__','Carolina_FromTheMotionPictureWhereTheCrawdadsSing_').replace('evermore_the_foreveristhesweetestcon_chapter','evermore_theforeveristhesweetestconchapter').replace('willow_90strendremix_.txt','/willow_90_strendremix_.txt')
    try:
        with open(path, 'r') as f:        
            txt = f.read()
            f.close()
        return txt
    except Exception as e:
        print(path)
        pass

In [49]:
df['lyrics'] = df.apply(get_lyrics, axis=1)
df.head()

./data/Albums/Midnights_TheLateNightEdition_/Anti_Hero.txt
./data/Albums/Midnights_TheLateNightEdition_/SnowOnTheBeach.txt
./data/Albums/Midnights_TheLateNightEdition_/YoureOnYourOwn_Kid.txt
./data/Albums/Midnights_TheLateNightEdition_/MidnightRain.txt
./data/Albums/Midnights_TheLateNightEdition_/Question____.txt
./data/Albums/Midnights_TheLateNightEdition_/VigilanteShit.txt
./data/Albums/Midnights_TheLateNightEdition_/Bejeweled.txt
./data/Albums/Midnights_TheLateNightEdition_/Labyrinth.txt
./data/Albums/Midnights_TheLateNightEdition_/Karma.txt
./data/Albums/Midnights_TheLateNightEdition_/SweetNothing.txt
./data/Albums/Midnights_TheLateNightEdition_/Mastermind.txt
./data/Albums/Midnights_TheLateNightEdition_/TheGreatWar.txt
./data/Albums/Midnights_TheLateNightEdition_/BiggerThanTheWholeSky.txt
./data/Albums/Midnights_TheLateNightEdition_/HighInfidelity.txt
./data/Albums/Midnights_TheLateNightEdition_/Wouldve_Couldve_Shouldve.txt
./data/Albums/Midnights_TheLateNightEdition_/DearReader.txt
./data/Albums/Midnights_TheLateNightEdition_/YoureLosingMe_FromTheVault_.txt
./data/Albums/Midnights_TheLateNightEdition_/SnowOnTheBeach_feat_MoreLanaDelRey_.txt
./data/Albums/Midnights_TheLateNightEdition_/Karma_Remix_.txt
./data/Albums/Midnights_TheTilDawnEdition_/LavenderHaze.txt
./data/Albums/Midnights_TheTilDawnEdition_/Maroon.txt
./data/Albums/Midnights_TheTilDawnEdition_/Anti_Hero.txt
./data/Albums/Midnights_TheTilDawnEdition_/SnowOnTheBeach.txt
./data/Albums/Midnights_TheTilDawnEdition_/YoureOnYourOwn_Kid.txt
./data/Albums/Midnights_TheTilDawnEdition_/MidnightRain.txt
./data/Albums/Midnights_TheTilDawnEdition_/Question____.txt
./data/Albums/Midnights_TheTilDawnEdition_/VigilanteShit.txt
./data/Albums/Midnights_TheTilDawnEdition_/Bejeweled.txt
./data/Albums/Midnights_TheTilDawnEdition_/Labyrinth.txt
./data/Albums/Midnights_TheTilDawnEdition_/Karma.txt
./data/Albums/Midnights_TheTilDawnEdition_/SweetNothing.txt
./data/Albums/Midnights_TheTilDawnEdition_/Mastermind.txt
./data/Albums/Midnights_TheTilDawnEdition_/TheGreatWar.txt
./data/Albums/Midnights_TheTilDawnEdition_/BiggerThanTheWholeSky.txt
./data/Albums/Midnights_TheTilDawnEdition_/Paris.txt
./data/Albums/Midnights_TheTilDawnEdition_/HighInfidelity.txt
./data/Albums/Midnights_TheTilDawnEdition_/Glitch.txt
./data/Albums/Midnights_TheTilDawnEdition_/Wouldve_Couldve_Shouldve.txt
./data/Albums/Midnights_TheTilDawnEdition_/DearReader.txt
./data/Albums/Midnights_TheTilDawnEdition_/HitsDifferent.txt
./data/Albums/Midnights_TheTilDawnEdition_/SnowOnTheBeach_feat_MoreLanaDelRey_.txt
./data/Albums/Midnights_TheTilDawnEdition_/Karma_Remix_.txt

,ID,Tracks,Album_ID,Album,Album_Path,lyrics
0,6688213,Mine (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,17 ContributorsTranslationsСрпскиEspañolPortug...
1,6688225,Sparks Fly (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,14 ContributorsTranslationsFrançaisСрпскиEspañ...
2,6688226,Back To December (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,14 ContributorsTranslationsFrançaisEspañolTürk...
3,6688227,Speak Now (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,9 ContributorsTranslationsEspañolFrançaisPortu...
4,6688228,Dear John (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,17 ContributorsTranslationsFrançaisEspañolTayl...

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          573 non-null    int64
 1   Tracks      573 non-null    object
 2   Album_ID    573 non-null    int64
 3   Album       573 non-null    object
 4   Album_Path  573 non-null    object
 5   lyrics      531 non-null    object
dtypes: int64(2), object(4)
memory usage: 27.0+ KB

In [51]:
print(f"{len(df['Album_ID'].value_counts())} Albums")
df['Album'].value_counts()

45 Albums

Album
Red (Taylor’s Version)                                                          31
Fearless (Taylor’s Version)                                                     27
Midnights (The Till Dawn Edition)                                               23
Midnights (The Til Dawn Edition)                                                23
Speak Now (Taylor’s Version)                                                    22
Midnights (The Late Night Edition)                                              21
Speak Now (Deluxe)                                                              20
Midnights (3am Edition)                                                         20
Fearless (Platinum Edition)                                                     19
Red                                                                             19
Reputation                                                                      19
evermore (Japanese Edition)                                                     19
evermore (digitally autographed fan edition)                                    18
evermore (deluxe version)                                                       18
Lover                                                                           18
folklore: the long pond studio sessions (Record Store Day Exclusive)            17
Folklore                                                                        16
Midnights (Target Exclusive)                                                    16
Taylor Swift                                                                    16
Evermore                                                                        15
Speak Now: World Tour Live                                                      14
Midnights (Apple Music Exclusive)                                               14
1989                                                                            14
Speak Now                                                                       14
Midnights                                                                       13
Lover (Live From Paris) Heart Shaped Vinyl                                       8
the “ladies lunching” chapter                                                    6
evermore: the “forever is the sweetest con” chapter                              6
evermore: the dropped your hand while dancing chapter                            6
Fearless (Taylor’s Version): The I Remember What You Said Last Night Chapter     6
Fearless (Taylor’s Version): The Halfway Out the Door Chapter                    6
Fearless (Taylor’s Version): The Kissing In The Rain Chapter                     6
Fearless (Taylor’s Version): The From the Vault Chapter                          6
The More Red (Taylor’s Version) Chapter                                          6
Red (Taylor’s Version): Could You Be The One Chapter                             6
Red (Taylor’s Version): She Wrote A Song About Me Chapter                        6
Red (Taylor’s Version): The Slow Motion Chapter                                  6
Red (Taylor’s Version): From The Vault Chapter                                   6
The More Fearless (Taylor’s Version) Chapter                                     5
Anti-Hero (Remixes)                                                              5
Lavender Haze (Remixes)                                                          5
The More Lover Chapter                                                           5
Message In A Bottle (Fat Max G Remix) (Taylor’s Version)                         2
the lakes - 7" Single (Record Store Day Exclusive)                               2
Carolina (From The Motion Picture “Where The Crawdads Sing”)                     2
All Too Well (10 Minute Version) [The Short Film] - EP                           1
Name: count, dtype: int64

Cleaning Lyrics

In [52]:
df.loc[0,'lyrics']

'17 ContributorsTranslationsСрпскиEspañolPortuguêsFrançaisTaylor Swift - Mine (Taylor’s Version) (Magyar Fordítás)ItalianoTaylor Swift - Mine (Taylor’s Version) (中文翻译)Taylor Swift - Mine (Taylor’s Version) (Türkçe Çeviri)Mine (Taylor’s Version) Lyrics[Intro]\nAh-ah, ah-ah\nAh-ah, ah-ah\n\n[Verse 1]\nYou were in college working part-time, waitin\' tables\nLeft a small town, never looked back\nI was a flight risk with a fear of falling\nWonderin\' why we bother with love if it never lasts\n\n[Pre-Chorus]\nI say, "Can you believe it?"\nAs we\'re lyin\' on the couch\nThe moment I could see it\nYes, yes, I can see it now\n\n[Chorus]\nDo you remember, we were sittin\' there by the water?\nYou put your arm around me for the first time\nYou made a rebel of a careless man\'s careful daughter\nYou are the best thing that\'s ever been mine\n\n[Verse 2]\nFlash forward and we\'re takin\' on the world together\nAnd there\'s a drawer of my things at your place\nYou learn my secrets and you figure out why I\'m guarded\nYou say we\'ll never make my parents\' mistakes\nYou might also like[Pre-Chorus]\nBut we got bills to pay\nWe got nothing figured out\nWhen it was hard to take\nYes, yes, this is what I thought about\n\n[Chorus]\nDo you remember, we were sittin\' there by the water?\nYou put your arm around me for the first time\nYou made a rebel of a careless man\'s careful daughter\nYou are the best thing that\'s ever been mine\nDo you remember all the city lights on the water?\nYou saw me start to believe for the first time\nYou made a rebel of a careless man\'s careful daughter\nYou are the best thing that\'s ever been mine\n\n[Post-Chorus]\nOh-oh, oh\n\n[Bridge]\nAnd I remember that fight, 2:30AM\nAs everything was slippin\' right out of our hands\nI ran out cryin\' and you followed me out into the street\nBraced myself for the goodbye\n\'Cause that\'s all I\'ve ever known\nThen you took me by surprise\nYou said, "I\'ll never leave you alone"\n[Chorus]\nYou said, "I remember how it felt sitting by the water\nAnd every time I look at you, it\'s like the first time\nI fell in love with a careless man\'s careful daughter\nShe is the best thing that\'s ever been mine"\n\n[Post-Chorus]\nHold on and make it last\nHold on, never turn back\n(Hold on) You made a rebel of a careless man\'s careful daughter\n(Hold on) You are the best thing that\'s ever been mine\n\n[Outro]\nYes, yes, do you believe it? (Hold on)\nYes, yes, we\'re gonna make it now (Hold on, yeah)\nYes, yes, and I can see it (Hold on)\nYes, yes, I can see it nowEmbed'

In [53]:
def remove_lyrics_header(lyrics):
    if lyrics is None:
        return None  # Return None if lyrics is None
    lyrics_list = lyrics.split('Lyrics', 1)  # split the string where 'Lyrics' occurs (because random info before)
    if len(lyrics_list) > 1:
        return lyrics_list[1]  # and, return the substring after 'Lyrics'
    else:
        return lyrics  # return the original string (whole string) if 'Lyrics' is not found


df["lyrics"] = df.lyrics.apply(lambda x: remove_lyrics_header(x))

In [54]:
df.head()

,ID,Tracks,Album_ID,Album,Album_Path,lyrics
0,6688213,Mine (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,"[Intro]\nAh-ah, ah-ah\nAh-ah, ah-ah\n\n[Verse ..."
1,6688225,Sparks Fly (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nThe way you move is like a full on ...
2,6688226,Back To December (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nI'm so glad you made time to see me...
3,6688227,Speak Now (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nI am not the kind of girl\nWho shou...
4,6688228,Dear John (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nLong were the nights\nWhen my days ...

Adding a field of the labels for parts of the song, to get a better idea of the songs' structures.

In [58]:
import re

def extract_labels(text):
    if text is None:
        return None  # Return None if text is None
    labels = re.findall(r'\[(.*?)\]', text)
    return labels

df["labels"] = df.lyrics.apply(lambda x: extract_labels(x))

In [60]:
df

,ID,Tracks,Album_ID,Album,Album_Path,lyrics,labels
0,6688213,Mine (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,"[Intro]\nAh-ah, ah-ah\nAh-ah, ah-ah\n\n[Verse ...","[Intro, Verse 1, Pre-Chorus, Chorus, Verse 2, ..."
1,6688225,Sparks Fly (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nThe way you move is like a full on ...,"[Verse 1, Chorus, Verse 2, Chorus, Bridge, Cho..."
2,6688226,Back To December (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nI'm so glad you made time to see me...,"[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Cho..."
3,6688227,Speak Now (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nI am not the kind of girl\nWho shou...,"[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Cho..."
4,6688228,Dear John (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nLong were the nights\nWhen my days ...,"[Verse 1, Chorus, Verse 2, Chorus, Instrumenta..."
...,...,...,...,...,...,...,...
568,8486447,"Wouldve, Couldve, Shouldve",1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,"[Verse 1]\nIf you would've blinked, then I wou...","[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Cho..."
569,8486436,Dear Reader,1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,"[Verse 1]\nDear reader, if it feels like a tra...","[Verse 1, Chorus, Verse 2, Chorus, Bridge, Outro]"
570,8461583,Hits Different,1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,[Verse 1]\nI washed my hands of us at the club...,"[Verse 1, Chorus, Post-Chorus, Verse 2, Chorus..."
571,9157481,Snow On The Beach (feat. More Lana Del Rey),1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,"[Verse 1: Taylor Swift]\nOne night, a few moon...","[Verse 1: Taylor Swift, Chorus: Taylor Swift, ..."
572,9157172,Karma (Remix),1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,"[Intro: Ice Spice]\nKarma is that girl, like (...","[Intro: Ice Spice, Verse 1: Taylor Swift, Pre-..."

In [64]:
df.loc[0,'labels']

['Intro',
 'Verse 1',
 'Pre-Chorus',
 'Chorus',
 'Verse 2',
 'Pre-Chorus',
 'Chorus',
 'Post-Chorus',
 'Bridge',
 'Chorus',
 'Post-Chorus',
 'Outro']

In [67]:
def clean_labels(labels):
    if labels is None:
        return None  # Return None if labels is None
    cleaned_labels = []
    for label in labels:
        if len(label.split(':')) > 1:
            cleaned_label = re.sub(r':.*$', '', label).strip()
            cleaned_labels.append(cleaned_label)
        else:
            cleaned_labels.append(label)
    return cleaned_labels

In [69]:
df["labels"] = df.labels.apply(lambda x: clean_labels(x))

In [70]:
df['labels'].value_counts()[:5]

labels
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Chorus, Outro]                            60
[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Chorus, Outro]    54
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Chorus]                                   43
[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Chorus]           18
[]                                                                                   11
Name: count, dtype: int64

In [71]:
df[df["labels"].str.len() == 0]

,ID,Tracks,Album_ID,Album,Album_Path,lyrics,labels
241,7291673,A Message From Taylor,758022,Red (Taylor’s Version),./data/Albums/Red_Taylor_sVersion_,"Musically and lyrically, Red resembled a heart...",[]
420,3331438,Reputation Magazine Vol. 1,350247,Reputation,./data/Albums/Reputation,5Embed,[]
421,3310416,Reputation [Prologue],350247,Reputation,./data/Albums/Reputation,Here's something I've learned about people.\n\...,[]
422,3312790,Why She Disappeared [Poem],350247,Reputation,./data/Albums/Reputation,"When she fell, she fell apart.\nCracked her bo...",[]
423,3312706,If Youre Anything Like Me [Poem],350247,Reputation,./data/Albums/Reputation,"If you're anything like me,\nYou bite your nai...",[]
487,5740070,Happy Face,14637,Speak Now: World Tour Live,./data/Albums/SpeakNow_WorldTourLive,SJW:\nAlways remember to do what you want and ...,[]
488,66567,Nexium,14637,Speak Now: World Tour Live,./data/Albums/SpeakNow_WorldTourLive,SJW:\nAlways remember to do what you want and ...,[]
492,5740071,The Gods,14637,Speak Now: World Tour Live,./data/Albums/SpeakNow_WorldTourLive,Drop that bridge like Taylor Swift\nGive this ...,[]
493,512291,Pack Kevorkian,14637,Speak Now: World Tour Live,./data/Albums/SpeakNow_WorldTourLive,"Couldn’t get a job, probably have to be a grad...",[]
496,100322,Like What Like Me,14637,Speak Now: World Tour Live,./data/Albums/SpeakNow_WorldTourLive,"(chorus)\n\nMan on the moon, if my dream works...",[]
500,66822,Suppository,14637,Speak Now: World Tour Live,./data/Albums/SpeakNow_WorldTourLive,"""I promis'd you an account of what befel me, a...",[]

In [72]:
df = df[df["labels"].str.len() != 0]
df.reset_index(inplace=True, drop=True)

In [73]:
df['labels'].value_counts()[:5]

labels
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Chorus, Outro]                            60
[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Chorus, Outro]    54
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Chorus]                                   43
[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Chorus]           18
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Verse 3, Chorus, Outro]                   11
Name: count, dtype: int64

In [75]:
all_labels_list = []
all_labels_list.extend(df['labels'])

In [79]:
from collections import Counter

# Filter out None values and flatten the list of lists
flattened_list = [label for sublist in all_labels_list if sublist is not None for label in sublist]

# Count occurrences of each label
c = Counter(flattened_list)
print(c)

Counter({'Chorus': 1491, 'Verse 1': 512, 'Verse 2': 511, 'Pre-Chorus': 500, 'Bridge': 466, 'Outro': 364, 'Post-Chorus': 223, 'Verse 3': 106, 'Intro': 74, 'Breakdown': 44, 'Refrain': 42, 'Chorus 1': 12, 'Instrumental Break': 11, 'Verse 4': 10, 'Verse 5': 8, 'Chorus 2': 6, 'Verse 6': 4, 'Break': 4, 'Guitar Solo': 4, 'Daffney Unger': 4, 'Buildup': 3, 'Pre-Chorus 2': 3, 'Spoken': 2, 'Interlude': 2, 'Non-Lyrical Break': 2, 'Verse': 2, 'Pre-Chorus 1': 2, 'Recorder click': 2, 'John Cena': 2, 'Kane': 2, 'John Tenta': 2, '1979': 2, 'Single Mix': 2, 'Remix': 2, 'Instrumental': 1, 'Chorus - Variation': 1, 'Pre-Chorus 3': 1, 'Video directed by Mark Romanek': 1, 'Instrumental bridge': 1, 'Spoken Outro': 1, 'Monty Brown': 1, 'WCW Halloween Havoc 98': 1, 'Mean Mitch Page': 1, 'formerly the Estonian ThunderFrog': 1, 'Devin and Mason Cutter': 1, 'Murder One and Rainman': 1, 'Blac and Blu': 1, 'Jeff McCready and Jimmy Lightning': 1, 'Dusty Rhodes': 1, 'Scott Hall': 1, 'Headbanger Mosh': 1, 'Barry Windham': 1, 'from GLOW': 1, 'Ryan Venkman and Johnny Stantz': 1, 'Chris Champion and Sean Royal': 1, 'Earl the Pearl and "Ramblin\'" Rich Myers': 1, 'Shynron and Kitsune': 1, 'Violent J': 1, 'Matt Borne': 1, 'Frank Champion and Shay Cash': 1, 'Melina': 1, '"The Funky Monkey" Angel Ortiz and "The Real Deal" Mike Draztic': 1, 'Brian Pillman': 1, 'Billy Jack Haynes': 1, '"Vintage" Vince Beach and "Retro" Reed James': 1, 'Eric Young': 1, 'from IPW Hardcore': 1, 'Loca and Delta Lotta Pain': 1, 'Jimmy Valiant in a mask': 1, 'Mondo Kleen': 1, 'Steve Corino and Jack Victory': 1, 'Allison Danger and Leva Bates': 1, 'Mr. Incredible and N.M.E.': 1, '"Delicious" Devin Blaze and "Terrific" Tommy Trainwreck': 1, 'Festus/Luke Gallows': 1, 'Kai Katana': 1, 'Australian wrestler': 1, 'from South East Professional Wrestling': 1, 'Cody Rhodes': 1, 'Jobber Dustin and Jobber Justin': 1, 'Austin Aries': 1, 'not the TNA character': 1, 'Saturyne': 1, 'Adam Revolver and Ted McNaler': 1, 'Roxie Cotton': 1, 'Firebreaker Chip and Todd Champion': 1, 'Brad Armstrong': 1, 'the Headbangers': 1, 'Dan Eckos and Sean Royal': 1, 'Dasher Hatfield': 1, 'Jim "The Anvil" Neidhart': 1, 'Bryan "Adam Bomb"/"Wrath" Clarke': 1, 'Shaggy 2 Dope': 1})

In [80]:
for key, value in c.items():
    if value<5:
        print(key)

Buildup
Instrumental
Spoken
Verse 6
Interlude
Non-Lyrical Break
Break
Verse
Guitar Solo
Chorus - Variation
Pre-Chorus 1
Pre-Chorus 2
Pre-Chorus 3
Video directed by Mark Romanek
Recorder click
Instrumental bridge
Spoken Outro
Daffney Unger
Monty Brown
WCW Halloween Havoc 98
John Cena
Mean Mitch Page
formerly the Estonian ThunderFrog
Devin and Mason Cutter
Murder One and Rainman
Blac and Blu
Jeff McCready and Jimmy Lightning
Dusty Rhodes
Scott Hall
Headbanger Mosh
Barry Windham
from GLOW
Ryan Venkman and Johnny Stantz
Chris Champion and Sean Royal
Earl the Pearl and "Ramblin'" Rich Myers
Shynron and Kitsune
Violent J
Matt Borne
Frank Champion and Shay Cash
Melina
"The Funky Monkey" Angel Ortiz and "The Real Deal" Mike Draztic
Brian Pillman
Kane
Billy Jack Haynes
"Vintage" Vince Beach and "Retro" Reed James
Eric Young
John Tenta
from IPW Hardcore
Loca and Delta Lotta Pain
Jimmy Valiant in a mask
Mondo Kleen
Steve Corino and Jack Victory
Allison Danger and Leva Bates
Mr. Incredible and N.M.E.
"Delicious" Devin Blaze and "Terrific" Tommy Trainwreck
Festus/Luke Gallows
Kai Katana
Australian wrestler
from South East Professional Wrestling
Cody Rhodes
Jobber Dustin and Jobber Justin
Austin Aries
not the TNA character
Saturyne
Adam Revolver and Ted McNaler
Roxie Cotton
Firebreaker Chip and Todd Champion
Brad Armstrong
the Headbangers
Dan Eckos and Sean Royal
Dasher Hatfield
Jim "The Anvil" Neidhart
Bryan "Adam Bomb"/"Wrath" Clarke
Shaggy 2 Dope
1979
Single Mix
Remix

In [81]:
to_remove='''Video directed by Mark Romanek
Recorder click
Daffney Unger
Monty Brown
WCW Halloween Havoc 98
John Cena
Mean Mitch Page
formerly the Estonian ThunderFrog
Devin and Mason Cutter
Murder One and Rainman
Blac and Blu
Jeff McCready and Jimmy Lightning
Dusty Rhodes
Scott Hall
Headbanger Mosh
Barry Windham
from GLOW
Ryan Venkman and Johnny Stantz
Chris Champion and Sean Royal
Earl the Pearl and "Ramblin'" Rich Myers
Shynron and Kitsune
Violent J
Matt Borne
Frank Champion and Shay Cash
Melina
"The Funky Monkey" Angel Ortiz and "The Real Deal" Mike Draztic
Brian Pillman
Kane
Billy Jack Haynes
"Vintage" Vince Beach and "Retro" Reed James
Eric Young
John Tenta
from IPW Hardcore
Loca and Delta Lotta Pain
Jimmy Valiant in a mask
Mondo Kleen
Steve Corino and Jack Victory
Allison Danger and Leva Bates
Mr. Incredible and N.M.E.
"Delicious" Devin Blaze and "Terrific" Tommy Trainwreck
Festus/Luke Gallows
Kai Katana
Australian wrestler
from South East Professional Wrestling
Cody Rhodes
Jobber Dustin and Jobber Justin
Austin Aries
not the TNA character
Saturyne
Adam Revolver and Ted McNaler
Roxie Cotton
Firebreaker Chip and Todd Champion
Brad Armstrong
the Headbangers
Dan Eckos and Sean Royal
Dasher Hatfield
Jim "The Anvil" Neidhart
Bryan "Adam Bomb"/"Wrath" Clarke
Shaggy 2 Dope
1979
Single Mix
Remix'''.split('\n')

In [82]:
def check_labels(labels_list):
    if set(to_remove).intersection(set(labels_list)):
        return True
    else:
        return False

In [85]:
def check_labels(labels):
    if labels is not None:
        if all(isinstance(label, str) and len(label) > 0 for label in labels):
            return True
    return False


df['weird_labels'] = df['labels'].apply(lambda x: check_labels(x))

/var/folders/fn/yld5z5p52q34cgp7bxwnlx580000gn/T/ipykernel_16114/2035383028.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weird_labels'] = df['labels'].apply(lambda x: check_labels(x))

In [86]:
df[df.weird_labels]

,ID,Tracks,Album_ID,Album,Album_Path,lyrics,labels,weird_labels
0,6688213,Mine (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,"[Intro]\nAh-ah, ah-ah\nAh-ah, ah-ah\n\n[Verse ...","[Intro, Verse 1, Pre-Chorus, Chorus, Verse 2, ...",True
1,6688225,Sparks Fly (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nThe way you move is like a full on ...,"[Verse 1, Chorus, Verse 2, Chorus, Bridge, Cho...",True
2,6688226,Back To December (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nI'm so glad you made time to see me...,"[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Cho...",True
3,6688227,Speak Now (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nI am not the kind of girl\nWho shou...,"[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Cho...",True
4,6688228,Dear John (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,[Verse 1]\nLong were the nights\nWhen my days ...,"[Verse 1, Chorus, Verse 2, Chorus, Instrumenta...",True
...,...,...,...,...,...,...,...,...
557,8486447,"Wouldve, Couldve, Shouldve",1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,"[Verse 1]\nIf you would've blinked, then I wou...","[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Cho...",True
558,8486436,Dear Reader,1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,"[Verse 1]\nDear reader, if it feels like a tra...","[Verse 1, Chorus, Verse 2, Chorus, Bridge, Outro]",True
559,8461583,Hits Different,1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,[Verse 1]\nI washed my hands of us at the club...,"[Verse 1, Chorus, Post-Chorus, Verse 2, Chorus...",True
560,9157481,Snow On The Beach (feat. More Lana Del Rey),1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,"[Verse 1: Taylor Swift]\nOne night, a few moon...","[Verse 1, Chorus, Post-Chorus, Verse 2, Chorus...",True
561,9157172,Karma (Remix),1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_,"[Intro: Ice Spice]\nKarma is that girl, like (...","[Intro, Verse 1, Pre-Chorus, Chorus, Verse 2, ...",True

In [87]:
df.loc[321,'lyrics'] = df.loc[321,'lyrics'].replace('[Video directed by Mark Romanek]','')
df.drop([410, 411, 412, 413, 414], inplace=True)

/var/folders/fn/yld5z5p52q34cgp7bxwnlx580000gn/T/ipykernel_16114/1588396874.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop([410, 411, 412, 413, 414], inplace=True)

In [88]:
df.reset_index(inplace=True, drop=True)

In [90]:
import re

def clean_text(text):
    if isinstance(text, str):
        cleaned_text = re.sub(r'\d+Embed$', '', text)
        return cleaned_text.strip()
    else:
        return text  # Return the original value if it's not a string

df.lyrics = df.lyrics.apply(lambda x: clean_text(x))

/var/folders/fn/yld5z5p52q34cgp7bxwnlx580000gn/T/ipykernel_16114/1636004150.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.lyrics = df.lyrics.apply(lambda x: clean_text(x))

In [91]:
df.labels.value_counts()[:10]

labels
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Chorus, Outro]                                                60
[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Chorus, Outro]                        53
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Chorus]                                                       43
[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Chorus]                               18
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Verse 3, Chorus, Outro]                                       11
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Outro]                                                         9
[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Breakdown, Chorus]                     9
[Intro, Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Post-Chorus, Bridge, Chorus, Outro]     9
[Verse 1, Chorus, Verse 2, Chorus, Bridge, Verse 3, Chorus]                                               8
[Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Pre-Chorus, Chorus, Outro]             8
Name: count, dtype: int64

In [96]:
all_labels_list = [label for sublist in df['labels'] if sublist is not None for label in sublist]
from collections import Counter
d = Counter(all_labels_list)

In [97]:
important_labels = []

for key, value in d.items():
    if value>50:
        important_labels.append(key)

In [98]:
important_labels

['Intro',
 'Verse 1',
 'Pre-Chorus',
 'Chorus',
 'Verse 2',
 'Post-Chorus',
 'Bridge',
 'Outro',
 'Verse 3']

In [99]:
remove_labels = []

for key, value in d.items():
    if value<50:
        remove_labels.append(key)
remove_labels

['Instrumental Break',
 'Buildup',
 'Breakdown',
 'Refrain',
 'Instrumental',
 'Spoken',
 'Verse 4',
 'Verse 5',
 'Verse 6',
 'Interlude',
 'Non-Lyrical Break',
 'Chorus 1',
 'Chorus 2',
 'Break',
 'Verse',
 'Guitar Solo',
 'Chorus - Variation',
 'Pre-Chorus 1',
 'Pre-Chorus 2',
 'Pre-Chorus 3',
 'Video directed by Mark Romanek',
 'Recorder click',
 'Instrumental bridge',
 'Spoken Outro',
 'Daffney Unger',
 'Monty Brown',
 'WCW Halloween Havoc 98',
 'John Cena',
 'Mean Mitch Page',
 'formerly the Estonian ThunderFrog',
 'Devin and Mason Cutter',
 'Murder One and Rainman',
 'Blac and Blu',
 'Jeff McCready and Jimmy Lightning',
 'Dusty Rhodes',
 'Scott Hall',
 'Headbanger Mosh',
 'Barry Windham',
 'from GLOW',
 'Ryan Venkman and Johnny Stantz',
 'Chris Champion and Sean Royal',
 'Earl the Pearl and "Ramblin\'" Rich Myers',
 'Shynron and Kitsune',
 'Violent J',
 'Matt Borne',
 'Frank Champion and Shay Cash',
 'Melina',
 '"The Funky Monkey" Angel Ortiz and "The Real Deal" Mike Draztic',
 'Brian Pillman',
 'Kane',
 'Billy Jack Haynes',
 '"Vintage" Vince Beach and "Retro" Reed James',
 'Eric Young',
 'John Tenta',
 'from IPW Hardcore',
 'Loca and Delta Lotta Pain',
 'Jimmy Valiant in a mask',
 'Mondo Kleen',
 'Steve Corino and Jack Victory',
 'Allison Danger and Leva Bates',
 'Mr. Incredible and N.M.E.',
 '"Delicious" Devin Blaze and "Terrific" Tommy Trainwreck',
 'Festus/Luke Gallows',
 'Kai Katana',
 'Australian wrestler',
 'from South East Professional Wrestling',
 'Cody Rhodes',
 'Jobber Dustin and Jobber Justin',
 'Austin Aries',
 'not the TNA character',
 'Saturyne',
 'Adam Revolver and Ted McNaler',
 'Roxie Cotton',
 'Firebreaker Chip and Todd Champion',
 'Brad Armstrong',
 'the Headbangers',
 'Dan Eckos and Sean Royal',
 'Dasher Hatfield',
 'Jim "The Anvil" Neidhart',
 'Bryan "Adam Bomb"/"Wrath" Clarke',
 'Shaggy 2 Dope',
 '1979',
 'Single Mix',
 'Remix']

In [100]:
df.to_csv('cleaned_songs_data.csv', index=False)