# Natural Language Processing - Lyric Analysis and Visualization

### Cleaning and Preparing Data

In [6]:
import numpy as np 
import pandas as pd 
import re
import os

In [7]:
path_to_album = './data/Albums/'
album_list = [os.path.join(path_to_album, album) for album in os.listdir(path_to_album)]
album_list

['./data/Albums/evermore_theforeveristhesweetestconchapter',
 './data/Albums/AllTooWell_10MinuteVersion__TheShortFilm__EP',
 './data/Albums/MessageInABottle_FatMaxGRemix__TaylorsVersion_',
 './data/Albums/Fearless_TaylorsVersion_',
 './data/Albums/Red_TaylorsVersion__CouldYouBeTheOneChapter',
 './data/Albums/TheMoreRed_TaylorsVersion_Chapter',
 './data/Albums/Carolina_FromTheMotionPictureWhereTheCrawdadsSing_',
 './data/Albums/LavenderHaze_Remixes_',
 './data/Albums/Red_TaylorsVersion__SheWroteASongAboutMeChapter',
 './data/Albums/Lover',
 './data/Albums/theladieslunchingchapter',
 './data/Albums/.DS_Store',
 './data/Albums/Midnights_TargetExclusive_',
 './data/Albums/Fearless_TaylorsVersion__TheHalfwayOuttheDoorChapter',
 './data/Albums/1989',
 './data/Albums/Red_TaylorsVersion__TheSlowMotionChapter',
 './data/Albums/Fearless_TaylorsVersion__TheIRememberWhatYouSaidLastNightChapter',
 './data/Albums/TaylorSwift',
 './data/Albums/Evermore',
 './data/Albums/evermore_JapaneseEdition_',
 './data/Albums/Reputation',
 './data/Albums/Midnights',
 './data/Albums/Midnights_TheTillDawnEdition_',
 './data/Albums/evermore_deluxeversion_',
 './data/Albums/Lover_LiveFromParis_HeartShapedVinyl',
 './data/Albums/folklore_thelongpondstudiosessions_RecordStoreDayExclusive_',
 './data/Albums/Red_TaylorsVersion_',
 './data/Albums/Anti_Hero_Remixes_',
 './data/Albums/Midnights_3amEdition_',
 './data/Albums/Red_TaylorsVersion__FromTheVaultChapter',
 './data/Albums/Red',
 './data/Albums/evermore_thedroppedyourhandwhiledancingchapter',
 './data/Albums/Folklore',
 './data/Albums/SpeakNow_WorldTourLive',
 './data/Albums/TheMoreLoverChapter',
 './data/Albums/Fearless_TaylorsVersion__TheFromtheVaultChapter',
 './data/Albums/SpeakNow_TaylorsVersion_',
 './data/Albums/SpeakNow_Deluxe_',
 './data/Albums/evermore_digitallyautographedfanedition_',
 './data/Albums/Midnights_AppleMusicExclusive_',
 './data/Albums/Fearless_PlatinumEdition_',
 './data/Albums/TheMoreFearless_TaylorsVersion_Chapter',
 './data/Albums/SpeakNow',
 './data/Albums/Fearless_TaylorsVersion__TheKissingInTheRainChapter',
 './data/Albums/Midnights_TheLateNightEdition_',
 './data/Albums/thelakes_7_Single_RecordStoreDayExclusive_',
 './data/Albums/Fearless']

The tabular folder has tables for each album and within each album folder we have songs. So, now, we will use the tabular table to map the paths above.

In [8]:
tabular_path = './data/Tabular/'
songs_list = [os.path.join(tabular_path, song) for song in os.listdir(tabular_path)]
songs_list

['./data/Tabular/SpeakNow_WorldTourLive.csv',
 './data/Tabular/Anti_Hero_Remixes_.csv',
 './data/Tabular/Red.csv',
 './data/Tabular/Fearless_PlatinumEdition_.csv',
 './data/Tabular/Fearless_Taylor_sVersion__TheKissingInTheRainChapter.csv',
 './data/Tabular/Red_Taylor_sVersion_.csv',
 './data/Tabular/Carolina_FromTheMotionPicture_WhereTheCrawdadsSing__.csv',
 './data/Tabular/LavenderHaze_Remixes_.csv',
 './data/Tabular/MessageInABottle_FatMaxGRemix__Taylor_sVersion_.csv',
 './data/Tabular/Midnights_AppleMusicExclusive_.csv',
 './data/Tabular/Red_Taylor_sVersion__FromTheVaultChapter.csv',
 './data/Tabular/Midnights_TheTilDawnEdition_.csv',
 './data/Tabular/Red_Taylor_sVersion__SheWroteASongAboutMeChapter.csv',
 './data/Tabular/Reputation.csv',
 './data/Tabular/Midnights_TargetExclusive_.csv',
 './data/Tabular/Fearless_Taylor_sVersion_.csv',
 './data/Tabular/TheMoreRed_Taylor_sVersion_Chapter.csv',
 './data/Tabular/folklore_thelongpondstudiosessions_RecordStoreDayExclusive_.csv',
 './data/Tabular/Red_Taylor_sVersion__CouldYouBeTheOneChapter.csv',
 './data/Tabular/Fearless_Taylor_sVersion__TheFromtheVaultChapter.csv',
 './data/Tabular/evermore_the_foreveristhesweetestcon_chapter.csv',
 './data/Tabular/SpeakNow.csv',
 './data/Tabular/SpeakNow_Taylor_sVersion_.csv',
 './data/Tabular/Midnights_TheTillDawnEdition_.csv',
 './data/Tabular/Fearless_Taylor_sVersion__TheIRememberWhatYouSaidLastNightChapter.csv',
 './data/Tabular/TheMoreFearless_Taylor_sVersion_Chapter.csv',
 './data/Tabular/Evermore.csv',
 './data/Tabular/Midnights_3amEdition_.csv',
 './data/Tabular/Lover_LiveFromParis_HeartShapedVinyl.csv',
 './data/Tabular/evermore_deluxeversion_.csv',
 './data/Tabular/Midnights.csv',
 './data/Tabular/evermore_JapaneseEdition_.csv',
 './data/Tabular/TaylorSwift.csv',
 './data/Tabular/Lover.csv',
 './data/Tabular/TheMoreLoverChapter.csv',
 './data/Tabular/evermore_digitallyautographedfanedition_.csv',
 './data/Tabular/thelakes_7_Single_RecordStoreDayExclusive_.csv',
 './data/Tabular/the_ladieslunching_chapter.csv',
 './data/Tabular/AllTooWell_10MinuteVersion__TheShortFilm__EP.csv',
 './data/Tabular/Midnights_TheLateNightEdition_.csv',
 './data/Tabular/Fearless_Taylor_sVersion__TheHalfwayOuttheDoorChapter.csv',
 './data/Tabular/Folklore.csv',
 './data/Tabular/Red_Taylor_sVersion__TheSlowMotionChapter.csv',
 './data/Tabular/SpeakNow_Deluxe_.csv',
 './data/Tabular/evermore_thedroppedyourhandwhiledancingchapter.csv',
 './data/Tabular/1989.csv']

In [10]:
album_df = pd.read_csv('./data/Albums.csv', index_col=0)
album_df.head()

        ID                                             Albums
0   758025                       Speak Now (Taylor’s Version)
1  1040217                 Midnights (The Late Night Edition)
2  1040211                   Midnights (The Til Dawn Edition)
3  1027134  folklore: the long pond studio sessions (Recor...
4  1013719            The More Red (Taylor’s Version) Chapter

In [11]:
album_df['Track_path'] = album_df.Albums.apply(lambda x : os.path.join(tabular_path, re.sub('[^a-zA-Z0-9_]','_',''.join(x.split()))+'.csv'))
album_df.head()

,ID,Albums,Track_path
0,758025,Speak Now (Taylor’s Version),./data/Tabular/SpeakNow_Taylor_sVersion_.csv
1,1040217,Midnights (The Late Night Edition),./data/Tabular/Midnights_TheLateNightEdition_.csv
2,1040211,Midnights (The Til Dawn Edition),./data/Tabular/Midnights_TheTilDawnEdition_.csv
3,1027134,folklore: the long pond studio sessions (Recor...,./data/Tabular/folklore_thelongpondstudiosessi...
4,1013719,The More Red (Taylor’s Version) Chapter,./data/Tabular/TheMoreRed_Taylor_sVersion_Chap...

In [12]:
album_df.loc[0,'Track_path']

'./data/Tabular/SpeakNow_Taylor_sVersion_.csv'

Fetching all songs within each album

In [19]:
df = pd.DataFrame()
for ind, album in enumerate(album_df['Track_path']):
    try:
        track_df = pd.read_csv(album)
        track_df['Album_ID'] = album_df.loc[ind]['ID']
        track_df['Album'] = album_df.loc[ind]['Albums']
        track_df['Album_Path'] = os.path.join(path_to_album, re.sub('[^a-zA-Z0-9_]','_',''.join(album_df.loc[ind]['Albums'].split())))
        df = pd.concat([df, track_df])
    except Exception as e:
        print('No songs in album: ',album )
        pass

df

,Unnamed: 0,ID,Tracks,Album_ID,Album,Album_Path
0,0,6688213,Mine (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
1,1,6688225,Sparks Fly (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
2,2,6688226,Back To December (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
3,3,6688227,Speak Now (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
4,4,6688228,Dear John (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_
...,...,...,...,...,...,...
18,18,8486447,"Wouldve, Couldve, Shouldve",1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_
19,19,8486436,Dear Reader,1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_
20,20,8461583,Hits Different,1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_
21,21,9157481,Snow On The Beach (feat. More Lana Del Rey),1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_
22,22,9157172,Karma (Remix),1040211,Midnights (The Till Dawn Edition),./data/Albums/Midnights_TheTillDawnEdition_

In [20]:
df.reset_index(drop=True, inplace=True)
df.drop('Unnamed: 0', axis=1, inplace=True)

In [24]:
df.loc[30,'Album_Path']

'./data/Albums/Midnights_TheLateNightEdition_'

In [25]:
df.loc[30,'Tracks']

'Bejeweled'

In [26]:
def get_lyrics(x):
    path = (x['Album_Path'] + '/' +re.sub('[^a-zA-Z0-9_]','_',''.join(x['Tracks'].split())) + '.txt').replace('_s', 's').replace('the_ladieslunching_chapter', 'theladieslunchingchapter').replace('Carolina_FromTheMotionPicture_WhereTheCrawdadsSing__','Carolina_FromTheMotionPictureWhereTheCrawdadsSing_').replace('evermore_the_foreveristhesweetestcon_chapter','evermore_theforeveristhesweetestconchapter').replace('willow_90strendremix_.txt','/willow_90_strendremix_.txt')
    try:
        with open(path, 'r') as f:        
            txt = f.read()
            f.close()
        return txt
    except Exception as e:
        print(path)
        pass

In [29]:
df['lyrics'] = df.apply(get_lyrics, axis=1)
df.head()

./data/Albums/Midnights_TheLateNightEdition_/Anti_Hero.txt
./data/Albums/Midnights_TheLateNightEdition_/SnowOnTheBeach.txt
./data/Albums/Midnights_TheLateNightEdition_/YoureOnYourOwn_Kid.txt
./data/Albums/Midnights_TheLateNightEdition_/MidnightRain.txt
./data/Albums/Midnights_TheLateNightEdition_/Question____.txt
./data/Albums/Midnights_TheLateNightEdition_/VigilanteShit.txt
./data/Albums/Midnights_TheLateNightEdition_/Bejeweled.txt
./data/Albums/Midnights_TheLateNightEdition_/Labyrinth.txt
./data/Albums/Midnights_TheLateNightEdition_/Karma.txt
./data/Albums/Midnights_TheLateNightEdition_/SweetNothing.txt
./data/Albums/Midnights_TheLateNightEdition_/Mastermind.txt
./data/Albums/Midnights_TheLateNightEdition_/TheGreatWar.txt
./data/Albums/Midnights_TheLateNightEdition_/BiggerThanTheWholeSky.txt
./data/Albums/Midnights_TheLateNightEdition_/HighInfidelity.txt
./data/Albums/Midnights_TheLateNightEdition_/Wouldve_Couldve_Shouldve.txt
./data/Albums/Midnights_TheLateNightEdition_/DearReader.txt
./data/Albums/Midnights_TheLateNightEdition_/YoureLosingMe_FromTheVault_.txt
./data/Albums/Midnights_TheLateNightEdition_/SnowOnTheBeach_feat_MoreLanaDelRey_.txt
./data/Albums/Midnights_TheLateNightEdition_/Karma_Remix_.txt
./data/Albums/Midnights_TheTilDawnEdition_/LavenderHaze.txt
./data/Albums/Midnights_TheTilDawnEdition_/Maroon.txt
./data/Albums/Midnights_TheTilDawnEdition_/Anti_Hero.txt
./data/Albums/Midnights_TheTilDawnEdition_/SnowOnTheBeach.txt
./data/Albums/Midnights_TheTilDawnEdition_/YoureOnYourOwn_Kid.txt
./data/Albums/Midnights_TheTilDawnEdition_/MidnightRain.txt
./data/Albums/Midnights_TheTilDawnEdition_/Question____.txt
./data/Albums/Midnights_TheTilDawnEdition_/VigilanteShit.txt
./data/Albums/Midnights_TheTilDawnEdition_/Bejeweled.txt
./data/Albums/Midnights_TheTilDawnEdition_/Labyrinth.txt
./data/Albums/Midnights_TheTilDawnEdition_/Karma.txt
./data/Albums/Midnights_TheTilDawnEdition_/SweetNothing.txt
./data/Albums/Midnights_TheTilDawnEdition_/Mastermind.txt
./data/Albums/Midnights_TheTilDawnEdition_/TheGreatWar.txt
./data/Albums/Midnights_TheTilDawnEdition_/BiggerThanTheWholeSky.txt
./data/Albums/Midnights_TheTilDawnEdition_/Paris.txt
./data/Albums/Midnights_TheTilDawnEdition_/HighInfidelity.txt
./data/Albums/Midnights_TheTilDawnEdition_/Glitch.txt
./data/Albums/Midnights_TheTilDawnEdition_/Wouldve_Couldve_Shouldve.txt
./data/Albums/Midnights_TheTilDawnEdition_/DearReader.txt
./data/Albums/Midnights_TheTilDawnEdition_/HitsDifferent.txt
./data/Albums/Midnights_TheTilDawnEdition_/SnowOnTheBeach_feat_MoreLanaDelRey_.txt
./data/Albums/Midnights_TheTilDawnEdition_/Karma_Remix_.txt

,ID,Tracks,Album_ID,Album,Album_Path,lyrics
0,6688213,Mine (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,17 ContributorsTranslationsСрпскиEspañolPortug...
1,6688225,Sparks Fly (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,14 ContributorsTranslationsFrançaisСрпскиEspañ...
2,6688226,Back To December (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,14 ContributorsTranslationsFrançaisEspañolTürk...
3,6688227,Speak Now (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,9 ContributorsTranslationsEspañolFrançaisPortu...
4,6688228,Dear John (Taylors Version),758025,Speak Now (Taylor’s Version),./data/Albums/SpeakNow_Taylor_sVersion_,17 ContributorsTranslationsFrançaisEspañolTayl...

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          573 non-null    int64
 1   Tracks      573 non-null    object
 2   Album_ID    573 non-null    int64
 3   Album       573 non-null    object
 4   Album_Path  573 non-null    object
 5   lyrics      531 non-null    object
dtypes: int64(2), object(4)
memory usage: 27.0+ KB

In [31]:
print(f"{len(df['Album_ID'].value_counts())} Albums")
df['Album'].value_counts()

45 Albums

Album
Red (Taylor’s Version)                                                          31
Fearless (Taylor’s Version)                                                     27
Midnights (The Till Dawn Edition)                                               23
Midnights (The Til Dawn Edition)                                                23
Speak Now (Taylor’s Version)                                                    22
Midnights (The Late Night Edition)                                              21
Speak Now (Deluxe)                                                              20
Midnights (3am Edition)                                                         20
Fearless (Platinum Edition)                                                     19
Red                                                                             19
Reputation                                                                      19
evermore (Japanese Edition)                                                     19
evermore (digitally autographed fan edition)                                    18
evermore (deluxe version)                                                       18
Lover                                                                           18
folklore: the long pond studio sessions (Record Store Day Exclusive)            17
Folklore                                                                        16
Midnights (Target Exclusive)                                                    16
Taylor Swift                                                                    16
Evermore                                                                        15
Speak Now: World Tour Live                                                      14
Midnights (Apple Music Exclusive)                                               14
1989                                                                            14
Speak Now                                                                       14
Midnights                                                                       13
Lover (Live From Paris) Heart Shaped Vinyl                                       8
the “ladies lunching” chapter                                                    6
evermore: the “forever is the sweetest con” chapter                              6
evermore: the dropped your hand while dancing chapter                            6
Fearless (Taylor’s Version): The I Remember What You Said Last Night Chapter     6
Fearless (Taylor’s Version): The Halfway Out the Door Chapter                    6
Fearless (Taylor’s Version): The Kissing In The Rain Chapter                     6
Fearless (Taylor’s Version): The From the Vault Chapter                          6
The More Red (Taylor’s Version) Chapter                                          6
Red (Taylor’s Version): Could You Be The One Chapter                             6
Red (Taylor’s Version): She Wrote A Song About Me Chapter                        6
Red (Taylor’s Version): The Slow Motion Chapter                                  6
Red (Taylor’s Version): From The Vault Chapter                                   6
The More Fearless (Taylor’s Version) Chapter                                     5
Anti-Hero (Remixes)                                                              5
Lavender Haze (Remixes)                                                          5
The More Lover Chapter                                                           5
Message In A Bottle (Fat Max G Remix) (Taylor’s Version)                         2
the lakes - 7" Single (Record Store Day Exclusive)                               2
Carolina (From The Motion Picture “Where The Crawdads Sing”)                     2
All Too Well (10 Minute Version) [The Short Film] - EP                           1
Name: count, dtype: int64